### ISSUE TITLE
KeyError: 'entities' on setup, following deprecated device_registry.devices usage warning (v0.9.3)

### ISSUE THREAD

**Issue by lionelser** [anotherjulien/MyHOME#224]
Since updating to (or running) v0.9.3, my F455 Gateway config entry fails to load with the following two related log entries.

1. Deprecation warning (immediately precedes the crash):

Code
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:348

Detected that custom integration 'myhome' uses `device_registry.devices` as a mapping or calls its lookup methods, which is deprecated; iterate it to get the device entries, or use `async_get`, `async_entries_for_config_entry` and similar helpers for lookups at custom_components/myhome/__init__.py, line 154: for device_entry in device_registry.devices.values(). This will stop working in Home Assistant 2027.9.0.

2. Setup failure:
Logger: homeassistant.config_entries
Source: config_entries.py:803

Error setting up entry F455 Gateway for myhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 803, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/__init__.py", line 164, in async_setup_entry
    for _entity_name in hass.data[DOMAIN][entry.data[CONF_MAC]][CONF_PLATFORMS][
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _platform
        ~~~~~~~~~
    ][_device][CONF_ENTITIES]:
    ~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'entities'

Environment:
Home Assistant Core: 2026.9.0
Home Assistant OS
MyHOME integration version: 0.9.3 (installed via HACS, latest available)
Installation type: Home Assistant OS, HACS 2.0.5
Steps already tried (no effect):
Reloading the config entry (config_entries.async_reload)
Full Home Assistant restart
Impact: The F455 Gateway config entry stays in setup_error state and all associated entities (lights, lock/unlock buttons) become unavailable/stale.
Happy to provide additional debug logs if needed.

**Comment by lionelser** [comment]
Update: Tried downgrading to v0.9.2 as a workaround, but it fails to even import on this HA Core version:
ImportError: cannot import name 'ENTITY_CATEGORY_CONFIG' from 'homeassistant.const'
(/usr/src/homeassistant/homeassistant/const.py)

Full chain: __init__.py → gateway.py → button.py imports ENTITY_CATEGORY_CONFIG from homeassistant.const, which no longer exists in HA Core 2026.9.0 (it was deprecated/removed upstream). So v0.9.2 is not a viable rollback target on current Core versions either — reverted back to v0.9.3, which at least loads up to the KeyError: 'entities' reported above.
Home Assistant Core: 2026.9.0

**Comment by GreenGrassBlueOcean** [comment]
Thank you for reporting this issue.

This issue has been resolved in the modernized **v2 architecture** developed under the new **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community organization:
- Addressed in **[Pull Request #232 (`v2-phase1-architecture`)](https://github.com/OpenWebNet-HA/MyHOME/pull/232)** and merged core commits.
- Resolved by declarative hardware profiles, token-bucket queue pacing, connection watchdog hardening, and canonical entity registry migration.

If you would like to test, please download or switch to the `v2-phase1-architecture` branch in HACS. If you encounter any remaining issues on this build, please feel free to report them in [PR #232](https://github.com/OpenWebNet-HA/MyHOME/pull/232).
